### ISSUE TITLE
Code to add App to device Home Screen and launch in full screen mode [$600]

### ISSUE THREAD

**Issue by DavidStodolsky** [DavidStodolsky/myturnb#2] opened 2015-03-04 20:15 UTC
Provide code to add App to Home Screen on iOS and Android.
Restructure MyTurn as a responsive full-screen web app.
This will also require correcting minor interface defect on the current MyTurn.mobi website.
Current defect is incorrect scrolling in discussion selection.
Code will run on the three most used mobile browsers: Chrome, Safari, and Android.
##

**Comment by dasher** [comment] 2015-05-05 05:16
Tested on:
  Android Tablet 5.1 and mobile 4.0.1
  iOS emulator iPad and iPhone

Git is double linking for some reason - the 2nd solution should be appearing in the pull requests

**Comment by DavidStodolsky** [comment] 2015-05-06 19:19
Do you have server resources where you can mount the code, so I can run tests via the Internet?

I have a third generation iPad and several Android phones that I can use for testing, as well as some OS X Macs. etc.

**Comment by jcomeauictx** [comment] 2017-04-16 01:58
I followed this for IOS and Android: https://developers.google.com/web/fundamentals/native-hardware/fullscreen/

tested on Android, doesn't go fullscreen as it should. need to do more testing to find out why.

**Comment by jcomeauictx** [comment] 2017-06-13 20:00
works on Android BLU phone. http://alpha.myturn.mobi/. goes fullscreen as intended.

**Comment by jcomeauictx** [comment] 2017-06-13 20:01
you need to close the issue for me to collect any of the bounty.

**Closed as completed** 2017-06-13 20:07 UTC
Labels: bounty
